from django.urls import path

from . import (
    album_views,
    dashboard_views,
    date_views,
    location_views,
    memory_views,
    note_views,
    notification_views,
    safety_views,
    settings_views,
    timeline_views,
    views,
)

urlpatterns = [
    path("health/", views.health, name="health"),
    path("dashboard/", dashboard_views.dashboard, name="dashboard"),
    path("notes/", note_views.note_list_create, name="note-list-create"),
    path("notes/<int:pk>/", note_views.note_detail, name="note-detail"),
    path("notes/<int:pk>/comments/", note_views.note_comments, name="note-comments"),
    path("notes/<int:pk>/comments/<int:comment_pk>/", note_views.note_comment_detail, name="note-comment-detail"),
    path("dates/", date_views.date_list_create, name="date-list-create"),
    path("dates/<int:pk>/", date_views.date_detail, name="date-detail"),
    path("memories/", memory_views.memory_list_create, name="memory-list-create"),
    path("memories/<int:pk>/", memory_views.memory_detail, name="memory-detail"),
    path("albums/", album_views.album_list_create, name="album-list-create"),
    path("albums/<int:pk>/", album_views.album_detail, name="album-detail"),
    path("albums/<int:pk>/add-photos/", album_views.album_add_photos, name="album-add-photos"),
    path("albums/<int:pk>/remove-photos/", album_views.album_remove_photos, name="album-remove-photos"),
    path("timeline/", timeline_views.timeline, name="timeline"),
    path("safety/check/", safety_views.safety_check, name="safety-check"),
    path("safety/history/", safety_views.safety_history, name="safety-history"),
    path("safety/latest/", safety_views.safety_latest, name="safety-latest"),
    path("location/start/", location_views.location_start, name="location-start"),
    path("location/update/", location_views.location_update, name="location-update"),
    path("location/stop/", location_views.location_stop, name="location-stop"),
    path("location/current/", location_views.location_current, name="location-current"),
    path("notifications/subscribe/", notification_views.subscribe, name="notif-subscribe"),
    path("notifications/unsubscribe/", notification_views.unsubscribe, name="notif-unsubscribe"),
    path("notifications/preferences/", notification_views.notification_preferences, name="notif-preferences"),
    path("notifications/vapid-key/", notification_views.vapid_public_key, name="notif-vapid-key"),
    path("settings/profile/", settings_views.profile_settings, name="settings-profile"),
    path("settings/couple/", settings_views.couple_settings, name="settings-couple"),
]
