# Generated by Django 5.1.15 on 2026-03-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="couple",
            name="relationship_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
