# Generated by Django 5.1.15 on 2026-03-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_relationship_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-is_pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="note",
            name="open_when_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("open_when_sad", "Open when sad"),
                    ("open_when_happy", "Open when happy"),
                    ("open_when_miss_me", "Open when you miss me"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
