# Generated by Django 5.1.15 on 2026-03-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_note_open_when"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importantdate",
            options={"ordering": ["date"]},
        ),
        migrations.RenameField(
            model_name="importantdate",
            old_name="label",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="importantdate",
            name="recurring",
        ),
        migrations.AddField(
            model_name="importantdate",
            name="date_type",
            field=models.CharField(
                choices=[
                    ("anniversary", "Anniversary"),
                    ("birthday", "Birthday"),
                    ("visit", "Visit"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
    ]
