# Generated by Django 5.1.15 on 2026-03-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_importantdate_title_type_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memory",
            options={"ordering": ["-created_at"], "verbose_name_plural": "memories"},
        ),
        migrations.AddField(
            model_name="memory",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="memories/thumbs/"),
        ),
    ]
