# Generated by Django 5.1.15 on 2026-03-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_memory_thumbnail_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="safecheckevent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="safecheckevent",
            name="acknowledged",
        ),
        migrations.RemoveField(
            model_name="safecheckevent",
            name="acknowledged_at",
        ),
        migrations.AddField(
            model_name="safecheckevent",
            name="message",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="safecheckevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("leaving", "Leaving now"),
                    ("reached", "Reached safely"),
                    ("check_in", "Quick check-in"),
                ],
                default="check_in",
                max_length=20,
            ),
        ),
    ]
