# Generated by Django 5.1.15 on 2026-03-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_safecheckevent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationsharesession",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="accuracy",
            field=models.FloatField(
                blank=True, help_text="Accuracy in meters", null=True
            ),
        ),
        migrations.AddField(
            model_name="locationsharesession",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationsharesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("stopped", "Stopped"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
