# Generated by Django 5.1.15 on 2026-03-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_push_and_notif_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="location_share_enabled",
            field=models.BooleanField(
                default=True, help_text="Allow partner to request location sharing"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="timezone",
            field=models.CharField(blank=True, default="UTC", max_length=50),
        ),
    ]
